-- T-005 / T-006 / T-007: knowledge documents, project members and canceled
-- requirements had no removal path at all. The hard part was never the missing
-- DELETE verb -- it is that each of the three lands on foreign keys with
-- different meanings. Some references are live permissions that must lapse when
-- someone leaves; others are accomplished facts and audit that must never be
-- destroyed. So the three resources get three strategies, and that inconsistency
-- is the conclusion rather than a compromise (D022).
--
-- Knowledge documents and project members are deleted outright: a chunk is
-- derived data that dies with its document, and the database was designed for
-- the member path from the start -- pull_request.author_user_id already carries
-- the only ON DELETE clause in the schema, precisely so that removing a member
-- clears the recomputable mapping while the immutable author snapshot survives.
--
-- A canceled requirement is soft-deleted instead, because ai_call_log and
-- pull_request_requirement_event hang off it. Destroying the row would destroy
-- the call audit and erase an accomplished PR association, which V5 went out of
-- its way to make impossible.

ALTER TABLE requirement ADD COLUMN deleted_at TIMESTAMPTZ;
ALTER TABLE requirement ADD COLUMN deleted_by BIGINT;

ALTER TABLE requirement ADD CONSTRAINT fk_requirement_deleted_by
    FOREIGN KEY (deleted_by) REFERENCES user_account (id);

-- A soft delete with no recorded actor is untraceable, and an actor with no
-- timestamp is not a deletion. Both columns are added NULL in the statements
-- above, so this CHECK sees (TRUE) = (TRUE) on every pre-existing row -- which
-- is the case V10MigrationTest exists to prove, because ADD CONSTRAINT ... CHECK
-- validates the rows already in the table and FoundationDatabaseTest only ever
-- migrates an empty schema.
ALTER TABLE requirement ADD CONSTRAINT ck_requirement_deleted_shape
    CHECK ((deleted_at IS NULL) = (deleted_by IS NULL));

-- One ledger for all three removals, because what has to be recorded is the same
-- shape three times over: who, when, what, and what else was revoked along with
-- it. R5 forbids writing the trace onto the deleted object, and two of the three
-- objects stop existing, so the record has to live somewhere else.
--
-- ARCHITECTURE.md 2.1 rules out a general audit_event table on the grounds that
-- a polymorphic entity_id cannot be constrained by a D006 composite foreign key.
-- That reasoning does not reach this table: the referenced rows are gone by
-- construction, so there is no target to point a foreign key at. What can be
-- constrained is, and resource_type is a closed three-value vocabulary rather
-- than an open registry. Splitting this into three narrow tables would not add a
-- single foreign key -- their resource ids dangle identically -- it would only
-- copy the same problem three times. See D022.
CREATE TABLE project_deletion_record (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id    BIGINT      NOT NULL,
    resource_type VARCHAR(32) NOT NULL,
    -- Deliberately carries no foreign key: after a hard delete there is nothing
    -- left to reference. Do not "tidy this up" later -- adding one would make it
    -- impossible to record the very deletions this table exists for.
    resource_id   BIGINT      NOT NULL,
    actor_user_id BIGINT      NOT NULL,
    -- Human-readable summary of what was revoked alongside the resource, e.g.
    -- "requirement assignments: 2; finding assignments: 5; scm bindings: 1".
    -- Nothing queries it; it is read by a person reconstructing a removal.
    detail        VARCHAR(500),
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_project_deletion_record_project
        FOREIGN KEY (project_id) REFERENCES project (id),
    CONSTRAINT fk_project_deletion_record_actor
        FOREIGN KEY (actor_user_id) REFERENCES user_account (id),
    -- This list and the DeletedResourceType enum are one vocabulary in two
    -- places. A value that reaches this CHECK aborts the whole insert, so the
    -- application maps onto the enum first and a test walks the entire enum
    -- against this list -- the same discipline finding.category needed.
    CONSTRAINT ck_project_deletion_record_resource_type
        CHECK (resource_type IN ('KNOWLEDGE_DOCUMENT', 'PROJECT_MEMBER', 'REQUIREMENT')),
    CONSTRAINT ck_project_deletion_record_resource_id_positive
        CHECK (resource_id > 0)
);

CREATE INDEX ix_project_deletion_record_project
    ON project_deletion_record (project_id, created_at DESC);
