-- Review results have had nowhere to go. A completed review sits in the product
-- until somebody thinks to look at it, which in practice means the loop that the
-- rest of this schema exists to enforce -- find, adjudicate, decide -- starts
-- late or not at all. One outbound channel per project fixes the notification
-- gap without inventing a general messaging subsystem, which ARCHITECTURE.md 7.1
-- explicitly rules out.
--
-- Why a table rather than one deployment-wide environment variable: a single
-- variable pushes every project's reviews into the same chat. That is wrong the
-- moment there are two projects, and this schema has been project-scoped
-- everywhere else from V2 onwards.

CREATE TABLE project_notification_channel (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id            BIGINT      NOT NULL,
    channel               VARCHAR(32) NOT NULL,
    -- The URL is a credential, not an address: a DingTalk robot webhook carries
    -- its access_token in the query string, so anyone holding the URL can post
    -- to that chat. It is therefore encrypted with the same AES-256-GCM key and
    -- the same cipher as scm_repository's token and secret, and it is never
    -- returned to a client -- the same write-only treatment V5 gave those two.
    encrypted_webhook_url TEXT        NOT NULL,
    -- The signing secret, required rather than optional. DingTalk offers three
    -- ways to protect a robot -- a keyword, an IP allowlist, or a signature --
    -- and only the signature survives the URL leaking, which is exactly the
    -- failure this column is here for. Making it NOT NULL removes the "just
    -- leave it blank" path that would quietly land on the weakest of the three.
    encrypted_secret      TEXT        NOT NULL,
    -- Lets a project stop notifications without destroying the credentials and
    -- having to paste them again. Deleting the row remains available and is the
    -- right move when the robot itself is being retired.
    enabled               BOOLEAN     NOT NULL DEFAULT TRUE,
    created_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_notification_channel_project
        FOREIGN KEY (project_id) REFERENCES project (id),
    -- One row per project per channel kind. It is a UNIQUE on the pair rather
    -- than on project_id alone so that a second channel kind can be added later
    -- without a migration that rewrites this constraint.
    CONSTRAINT uq_notification_channel_project_channel
        UNIQUE (project_id, channel),
    -- This list and the NotificationChannelType enum are one vocabulary in two
    -- places, the same discipline finding.category and
    -- project_deletion_record.resource_type needed: a value that reaches this
    -- CHECK aborts the whole insert, so the application maps onto the enum first
    -- and a test walks the entire enum against this list.
    CONSTRAINT ck_notification_channel_type
        CHECK (channel IN ('DINGTALK'))
);
