-- Batch 1 (Phase 2): local accounts, projects and project members.
-- Column set and constraints follow docs/v2/ARCHITECTURE.md 2.1 / 2.3 / 2.4.
-- No ON DELETE is declared anywhere: 2.3 does not define deletion semantics for
-- these tables, and batch 1 exposes no hard-delete endpoint.

CREATE TABLE user_account (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username        VARCHAR(64)  NOT NULL,
    password_hash   VARCHAR(255) NOT NULL,
    enabled         BOOLEAN      NOT NULL DEFAULT TRUE,
    session_version INTEGER      NOT NULL DEFAULT 0,
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT uq_user_account_username UNIQUE (username),
    CONSTRAINT ck_user_account_session_version_non_negative CHECK (session_version >= 0)
);

-- No separate UNIQUE (id) is declared on project: the primary key already is the
-- unique key that (project_id) -> project (id) references, and a second identical
-- index would only cost writes.
CREATE TABLE project (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(120) NOT NULL,
    created_by BIGINT       NOT NULL,
    status     VARCHAR(32)  NOT NULL,
    created_at TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT fk_project_created_by FOREIGN KEY (created_by) REFERENCES user_account (id),
    CONSTRAINT ck_project_status CHECK (status IN ('ACTIVE', 'ARCHIVED'))
);

-- Batch 1 only ever writes ACTIVE; ARCHIVED is reserved by the column contract
-- in ARCHITECTURE.md 2.1 and has no transition implemented yet.

CREATE TABLE project_member (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id               BIGINT      NOT NULL,
    user_id                  BIGINT      NOT NULL,
    role                     VARCHAR(32) NOT NULL,
    scm_external_user_id     VARCHAR(128),
    scm_username             VARCHAR(128),
    scm_identity_verified_at TIMESTAMPTZ,
    created_at               TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at               TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_project_member_project FOREIGN KEY (project_id) REFERENCES project (id),
    CONSTRAINT fk_project_member_user    FOREIGN KEY (user_id)    REFERENCES user_account (id),
    CONSTRAINT ck_project_member_role CHECK (role IN ('LEADER', 'DEVELOPER', 'REVIEWER')),
    -- Composite target for every project-scoped reference to a member (2.3).
    CONSTRAINT uq_project_member_project_user UNIQUE (project_id, user_id),
    -- The SCM identity is the authorization key (D010); usernames are display only.
    CONSTRAINT uq_project_member_project_scm_external_user
        UNIQUE (project_id, scm_external_user_id)
);

-- At most one LEADER per project. PostgreSQL can only express a partial
-- uniqueness rule as a unique index, never as a table constraint. The "at least
-- one LEADER" half is a per-commit Service invariant (D004, clarified by D013.9)
-- because no immediate constraint can express it.
CREATE UNIQUE INDEX ux_project_member_single_leader
    ON project_member (project_id) WHERE role = 'LEADER';

CREATE INDEX ix_project_member_user ON project_member (user_id);
