-- Batch 1 (Phase 3): requirements, immutable revisions and acceptance criteria.
-- Column set and constraints follow docs/v2/ARCHITECTURE.md 2.1 / 2.3 / 2.4.
-- Every project-scoped reference carries project_id (D006). No ON DELETE is
-- declared: 2.3 does not define deletion semantics and batch 1 exposes no
-- hard-delete endpoint.

CREATE TABLE requirement (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id          BIGINT      NOT NULL,
    assignee_id         BIGINT,
    status              VARCHAR(32) NOT NULL,
    current_revision_id BIGINT,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_requirement_project FOREIGN KEY (project_id) REFERENCES project (id),
    CONSTRAINT ck_requirement_status
        CHECK (status IN ('DRAFT', 'READY', 'IN_DEVELOPMENT', 'DONE', 'CANCELED')),
    -- Composite target so project-scoped children can prove same-project parentage.
    CONSTRAINT uq_requirement_project_id UNIQUE (project_id, id),
    -- The assignee must be a member of the same project (2.3).
    CONSTRAINT fk_requirement_assignee FOREIGN KEY (project_id, assignee_id)
        REFERENCES project_member (project_id, user_id)
);

CREATE TABLE requirement_revision (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id         BIGINT      NOT NULL,
    requirement_id     BIGINT      NOT NULL,
    seq                INTEGER     NOT NULL,
    title              VARCHAR(200) NOT NULL,
    background         TEXT,
    description        TEXT,
    created_by         BIGINT      NOT NULL,
    change_reason      TEXT,
    created_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
    quality_json       JSONB,
    quality_version    VARCHAR(32),
    quality_checked_at TIMESTAMPTZ,
    CONSTRAINT fk_requirement_revision_requirement FOREIGN KEY (project_id, requirement_id)
        REFERENCES requirement (project_id, id),
    -- Audit actors point at the global account: leaving a project must not erase
    -- an accomplished fact (2.3).
    CONSTRAINT fk_requirement_revision_created_by FOREIGN KEY (created_by)
        REFERENCES user_account (id),
    CONSTRAINT ck_requirement_revision_seq_positive CHECK (seq >= 1),
    CONSTRAINT uq_requirement_revision_requirement_seq UNIQUE (requirement_id, seq),
    CONSTRAINT uq_requirement_revision_project_id UNIQUE (project_id, id),
    -- Three-column target for requirement.current_revision_id: one foreign key
    -- proves same project, correct parent and existence at once.
    CONSTRAINT uq_requirement_revision_project_requirement_id
        UNIQUE (project_id, requirement_id, id)
);

-- The requirement <-> revision cycle is broken by a nullable current_revision_id
-- under MATCH SIMPLE: while the column is NULL the whole composite key is skipped,
-- so the three-step insert (requirement -> revision -> backfill) works without
-- DEFERRABLE. Measured in research/pg15-hibernate-constraints.md item 2.
-- MATCH FULL is forbidden here: it rejects mixed null/non-null keys outright and
-- would make the backfill design impossible (D013.10).
ALTER TABLE requirement
    ADD CONSTRAINT fk_requirement_current_revision
    FOREIGN KEY (project_id, id, current_revision_id)
    REFERENCES requirement_revision (project_id, requirement_id, id);

CREATE TABLE acceptance_criterion (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id              BIGINT      NOT NULL,
    requirement_revision_id BIGINT      NOT NULL,
    ac_key                  VARCHAR(64) NOT NULL,
    sort_order              INTEGER     NOT NULL,
    text                    TEXT        NOT NULL,
    created_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_acceptance_criterion_revision FOREIGN KEY (project_id, requirement_revision_id)
        REFERENCES requirement_revision (project_id, id),
    -- ac_key is the stable cross-revision business identity; sort_order is display
    -- only and must never be used as identity (D011).
    CONSTRAINT uq_acceptance_criterion_revision_key UNIQUE (requirement_revision_id, ac_key),
    CONSTRAINT uq_acceptance_criterion_project_id UNIQUE (project_id, id),
    CONSTRAINT uq_acceptance_criterion_project_revision_id
        UNIQUE (project_id, requirement_revision_id, id)
);

CREATE INDEX ix_requirement_project_status ON requirement (project_id, status);
CREATE INDEX ix_requirement_revision_requirement ON requirement_revision (project_id, requirement_id);
CREATE INDEX ix_acceptance_criterion_revision ON acceptance_criterion (project_id, requirement_revision_id);
