-- Batch 2 (Phase 4): knowledge documents, chunks with their vectors, and the AI
-- call log. Column set and constraints follow docs/v2/ARCHITECTURE.md 2.1 / 2.3
-- / 2.4, with the two additions and the enum values ruled in design.md 2.1.
--
-- No ON DELETE is declared here: 2.3 defines deletion semantics only for
-- pull_request.author_user_id (see V5), and nowhere else.

CREATE TABLE knowledge_document (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id            BIGINT       NOT NULL,
    source_type           VARCHAR(32)  NOT NULL,
    -- NULL means public project knowledge; non-NULL means it belongs to that
    -- requirement and is only visible to that requirement's AI scenarios (D005).
    source_requirement_id BIGINT,
    title                 VARCHAR(255) NOT NULL,
    text                  TEXT,
    status                VARCHAR(32)  NOT NULL,
    failure_reason        TEXT,
    created_at            TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at            TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT fk_knowledge_document_project FOREIGN KEY (project_id) REFERENCES project (id),
    CONSTRAINT fk_knowledge_document_requirement
        FOREIGN KEY (project_id, source_requirement_id) REFERENCES requirement (project_id, id),
    CONSTRAINT ck_knowledge_document_source_type
        CHECK (source_type IN ('REQUIREMENT_ATTACHMENT', 'PROJECT_KNOWLEDGE')),
    CONSTRAINT ck_knowledge_document_status
        CHECK (status IN ('PENDING', 'READY', 'FAILED')),
    -- 2.1: the attachment type and its ownership must agree. Without this a row
    -- could claim to be public knowledge while pointing at a requirement, and
    -- the attachment foreign key below would still accept it.
    CONSTRAINT ck_knowledge_document_scope_matches_type
        CHECK ((source_type = 'REQUIREMENT_ATTACHMENT' AND source_requirement_id IS NOT NULL)
            OR (source_type = 'PROJECT_KNOWLEDGE' AND source_requirement_id IS NULL)),
    -- A document is only READY once its text has been extracted, and only FAILED
    -- with a reason to show (ARCHITECTURE.md 6 requires displaying it).
    CONSTRAINT ck_knowledge_document_ready_has_text
        CHECK (status <> 'READY' OR text IS NOT NULL),
    CONSTRAINT ck_knowledge_document_failed_has_reason
        CHECK (status <> 'FAILED' OR failure_reason IS NOT NULL),
    CONSTRAINT uq_knowledge_document_project_id UNIQUE (project_id, id),
    -- The target of requirement_attachment's three-column key below. Without it
    -- that foreign key has nothing to reference.
    CONSTRAINT uq_knowledge_document_project_id_scope
        UNIQUE (project_id, id, source_requirement_id)
);

-- Both foreign key columns are NOT NULL and that is load-bearing, not tidiness
-- (D015.2). Measured: under MATCH SIMPLE a NULL in requirement_id makes
-- PostgreSQL skip the entire three-column check, after which a document_id that
-- exists nowhere is accepted. That key is the only enforcer of D005's ownership
-- rule, so making it skippable would reduce it to decoration.
CREATE TABLE requirement_attachment (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id     BIGINT      NOT NULL,
    requirement_id BIGINT      NOT NULL,
    document_id    BIGINT      NOT NULL,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_requirement_attachment_requirement
        FOREIGN KEY (project_id, requirement_id) REFERENCES requirement (project_id, id),
    -- Pins the document's own scope to exactly this row's requirement, so a
    -- public-knowledge document (scope NULL) can never be attached: 23503.
    CONSTRAINT fk_requirement_attachment_document_scope
        FOREIGN KEY (project_id, document_id, requirement_id)
        REFERENCES knowledge_document (project_id, id, source_requirement_id),
    CONSTRAINT uq_requirement_attachment_pair UNIQUE (requirement_id, document_id),
    -- A document belongs to at most one requirement (2.1).
    CONSTRAINT uq_requirement_attachment_document UNIQUE (project_id, document_id)
);

CREATE TABLE knowledge_chunk (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id  BIGINT      NOT NULL,
    document_id BIGINT      NOT NULL,
    seq         INTEGER     NOT NULL,
    content     TEXT        NOT NULL,
    metadata    JSONB,
    -- Deliberately dimensionless (D001): the model's dimension is deployment
    -- configuration, and binding it here would make the same Flyway version
    -- produce different structures in different environments.
    embedding   VECTOR,
    provider    VARCHAR(64),
    model       VARCHAR(128),
    version     VARCHAR(64),
    dimension   INTEGER,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_knowledge_chunk_document
        FOREIGN KEY (project_id, document_id) REFERENCES knowledge_document (project_id, id),
    CONSTRAINT ck_knowledge_chunk_seq_positive CHECK (seq >= 1),
    CONSTRAINT uq_knowledge_chunk_document_seq UNIQUE (document_id, seq),
    -- Self-consistency only, and it binds no particular dimension, so it stays
    -- compatible with D001. It cannot catch a whole column embedded at the wrong
    -- dimension: measured, a dimensionless column is not checked by the database
    -- at all until an index exists, and one mismatched row makes every TopK query
    -- in that project fail. ARCHITECTURE.md 5's "the application validates
    -- dimension on write" is therefore the only real defence (D015.3).
    CONSTRAINT ck_knowledge_chunk_dimension
        CHECK (embedding IS NULL OR dimension = vector_dims(embedding))
);

-- No vector index. Measured: ivfflat and hnsw both fail on a dimensionless
-- column with 22023 (column does not have dimensions), so D001 and an index
-- cannot both hold in this batch. The expression-index route arrives with the
-- phase that freezes an embedding profile.

CREATE TABLE ai_call_log (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id              BIGINT      NOT NULL,
    -- Column now, foreign key in batch 3 (D015.1): review does not exist yet.
    -- This is not an oversight. Nothing in batch 2 writes it, so it must be
    -- entirely NULL when batch 3 adds
    --   FOREIGN KEY (project_id, review_id) -> review (project_id, id)
    -- and that migration must assert so before adding the constraint.
    review_id               BIGINT,
    requirement_id          BIGINT,
    requirement_revision_id BIGINT,
    use_case                VARCHAR(32) NOT NULL,
    model                   VARCHAR(128) NOT NULL,
    -- Split rather than one total (design.md 2.1): Phase 8 reports token cost,
    -- and a single summed number cannot be taken apart afterwards.
    prompt_token            INTEGER,
    completion_token        INTEGER,
    total_token             INTEGER,
    latency_ms              INTEGER     NOT NULL,
    status                  VARCHAR(32) NOT NULL,
    error                   TEXT,
    created_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_ai_call_log_project FOREIGN KEY (project_id) REFERENCES project (id),
    CONSTRAINT fk_ai_call_log_requirement
        FOREIGN KEY (project_id, requirement_id) REFERENCES requirement (project_id, id),
    -- Both keys are kept on purpose: when requirement_revision_id is NULL,
    -- MATCH SIMPLE skips this three-column key and the two-column one above
    -- still holds the requirement to this project.
    CONSTRAINT fk_ai_call_log_revision
        FOREIGN KEY (project_id, requirement_id, requirement_revision_id)
        REFERENCES requirement_revision (project_id, requirement_id, id),
    CONSTRAINT ck_ai_call_log_use_case
        CHECK (use_case IN ('REQUIREMENT_QUALITY', 'IMPLEMENTATION_GUIDANCE', 'EMBEDDING', 'REVIEW')),
    CONSTRAINT ck_ai_call_log_status
        CHECK (status IN ('SUCCESS', 'FAILED', 'TIMEOUT')),
    CONSTRAINT ck_ai_call_log_latency_non_negative CHECK (latency_ms >= 0)
);

CREATE INDEX ix_knowledge_document_project_status ON knowledge_document (project_id, status);
CREATE INDEX ix_knowledge_document_scope ON knowledge_document (project_id, source_requirement_id);
CREATE INDEX ix_knowledge_chunk_document ON knowledge_chunk (project_id, document_id);
CREATE INDEX ix_requirement_attachment_requirement ON requirement_attachment (project_id, requirement_id);
CREATE INDEX ix_ai_call_log_project_created ON ai_call_log (project_id, created_at);
