-- Batch 2 (Phase 5): the project's active SCM repository, the authoritative PR
-- snapshot, and the audit of PR-to-requirement association changes. Column set
-- and constraints follow docs/v2/ARCHITECTURE.md 2.1 / 2.3 / 3.1, with the
-- rulings in design.md 3.
--
-- This file declares the one ON DELETE in the whole schema. That is not a
-- reversal of batch 1's rule: the rule was always "write what 2.3 specifies",
-- and 2.3 specifies deletion semantics for pull_request.author_user_id and for
-- nothing else.

CREATE TABLE scm_repository (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id        BIGINT       NOT NULL,
    provider          VARCHAR(32)  NOT NULL,
    -- Normalized per design.md 3.1: lowercase host, default port and trailing
    -- slash dropped, IDN in punycode, api.github.com folded to github.com. It is
    -- stored rather than derived because it freezes once a PR exists, and a
    -- derivation rule that changed later would silently re-identify repositories.
    instance_identity VARCHAR(255) NOT NULL,
    external_id       VARCHAR(128) NOT NULL,
    api_base          VARCHAR(512) NOT NULL,
    encrypted_token   TEXT         NOT NULL,
    encrypted_secret  TEXT         NOT NULL,
    created_at        TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at        TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT fk_scm_repository_project FOREIGN KEY (project_id) REFERENCES project (id),
    CONSTRAINT ck_scm_repository_provider CHECK (provider IN ('GITHUB', 'GITLAB')),
    -- One active repository per project (2.1).
    CONSTRAINT uq_scm_repository_project UNIQUE (project_id),
    -- Composite target for pull_request below.
    CONSTRAINT uq_scm_repository_project_id UNIQUE (project_id, id),
    -- Global, deliberately without project_id (design.md 3.6). Webhook delivery
    -- is routed by the repository identity inside the payload, so if two projects
    -- could register one repository a single delivery would have two targets and
    -- two secrets, and no signature check would be well defined.
    CONSTRAINT uq_scm_repository_stable_identity
        UNIQUE (provider, instance_identity, external_id)
);

-- GITLAB is reserved by the provider CHECK for Phase 8; batch 2 implements only
-- GITHUB. Freezing the value now costs nothing and avoids a later migration.

CREATE TABLE pull_request (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id               BIGINT       NOT NULL,
    repository_id            BIGINT       NOT NULL,
    external_number          INTEGER      NOT NULL,
    base_sha                 VARCHAR(64)  NOT NULL,
    head_sha                 VARCHAR(64)  NOT NULL,
    -- SHA-256 hex of the canonicalized review input (design.md 3.2). Its inputs
    -- are the repository identity, base/head and the changed-file manifest with
    -- every patch -- never source_revision or source_updated_at, which 3.1
    -- restricts to event ordering and which must not mint a new identity.
    review_input_fingerprint VARCHAR(64)  NOT NULL,
    -- Ordering only: an older delivery must never roll head, base or the patches
    -- backwards (3.1).
    source_revision          VARCHAR(128),
    source_updated_at        TIMESTAMPTZ,
    -- The manifest and every patch (D015.7). Stored rather than re-fetched at
    -- review time, because the fingerprint's inputs must stay reproducible from
    -- the database -- otherwise the "authoritative snapshot" is not a snapshot.
    changed_files            JSONB        NOT NULL,
    requirement_id           BIGINT,
    -- Immutable snapshot of who opened it, as the provider reported.
    author_external_user_id  VARCHAR(128) NOT NULL,
    author_username          VARCHAR(128) NOT NULL,
    -- Recomputable mapping to a project member. Never the authorization key on
    -- its own: "is this my PR" is decided by the external id (D010).
    author_user_id           BIGINT,
    created_at               TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at               TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT fk_pull_request_repository
        FOREIGN KEY (project_id, repository_id) REFERENCES scm_repository (project_id, id),
    CONSTRAINT fk_pull_request_requirement
        FOREIGN KEY (project_id, requirement_id) REFERENCES requirement (project_id, id),
    -- The column list on SET NULL is required, not decoration: without it
    -- PostgreSQL would also try to null project_id, which is NOT NULL. PostgreSQL
    -- 15 is the first release with this form, and it is exactly what 2.3 asks for.
    CONSTRAINT fk_pull_request_author
        FOREIGN KEY (project_id, author_user_id) REFERENCES project_member (project_id, user_id)
        ON DELETE SET NULL (author_user_id),
    CONSTRAINT ck_pull_request_external_number_positive CHECK (external_number >= 1),
    CONSTRAINT uq_pull_request_repository_number UNIQUE (repository_id, external_number),
    CONSTRAINT uq_pull_request_project_id UNIQUE (project_id, id)
);

CREATE TABLE pull_request_requirement_event (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id          BIGINT      NOT NULL,
    pull_request_id     BIGINT      NOT NULL,
    from_requirement_id BIGINT,
    to_requirement_id   BIGINT,
    actor_type          VARCHAR(16) NOT NULL,
    actor_user_id       BIGINT,
    reason              TEXT,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_pr_requirement_event_pull_request
        FOREIGN KEY (project_id, pull_request_id) REFERENCES pull_request (project_id, id),
    CONSTRAINT fk_pr_requirement_event_from
        FOREIGN KEY (project_id, from_requirement_id) REFERENCES requirement (project_id, id),
    CONSTRAINT fk_pr_requirement_event_to
        FOREIGN KEY (project_id, to_requirement_id) REFERENCES requirement (project_id, id),
    -- The audit actor points at the global account: leaving a project must not
    -- erase an accomplished fact (2.3).
    CONSTRAINT fk_pr_requirement_event_actor FOREIGN KEY (actor_user_id) REFERENCES user_account (id),
    CONSTRAINT ck_pr_requirement_event_actor_type CHECK (actor_type IN ('USER', 'SYSTEM')),
    -- 2.1: the type and actor combination must be legal. A person acted, or the
    -- system did; there is no third case and no anonymous human.
    CONSTRAINT ck_pr_requirement_event_actor_matches_type
        CHECK ((actor_type = 'USER' AND actor_user_id IS NOT NULL)
            OR (actor_type = 'SYSTEM' AND actor_user_id IS NULL)),
    -- The table records changes only (2.1 is emphatic about 仅), so a row with
    -- neither side is not a change and a row with both sides equal is a no-op.
    CONSTRAINT ck_pr_requirement_event_is_a_change
        CHECK ((from_requirement_id IS NOT NULL OR to_requirement_id IS NOT NULL)
            AND from_requirement_id IS DISTINCT FROM to_requirement_id)
);

CREATE INDEX ix_pull_request_requirement ON pull_request (project_id, requirement_id);
CREATE INDEX ix_pull_request_head_sha ON pull_request (project_id, head_sha);
CREATE INDEX ix_pr_requirement_event_pull_request
    ON pull_request_requirement_event (project_id, pull_request_id);
