-- Batch 3 (Phase 6 + 7): the last three tables. After this migration the schema
-- holds exactly 16 tables and no further table may be added.
--
-- Column sets and constraints follow docs/v2/ARCHITECTURE.md 2.1 / 2.2 / 2.3 /
-- 3.1 / 3.2, with the rulings in design.md 4 and 6, each of which is backed by a
-- measurement in research/finding-constraint-trigger-measured.md or
-- research/fencing-and-concurrency-measured.md.
--
-- No ON DELETE anywhere in this file. 2.3 defines deletion semantics only for
-- pull_request.author_user_id, which V5 already declared.

CREATE TABLE review (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id               BIGINT       NOT NULL,
    pull_request_id          BIGINT       NOT NULL,
    -- The four identity columns (3.1). They are immutable after creation, and
    -- trg_review_identity_immutable below enforces that rather than merely
    -- asserting it: changing one turns this row into a different Review.
    head_sha                 VARCHAR(64)  NOT NULL,
    review_input_fingerprint VARCHAR(64)  NOT NULL,
    requirement_id           BIGINT,
    requirement_revision_id  BIGINT,
    -- Execution status. 3.2: PENDING -> RUNNING -> COMPLETED | FAILED, with
    -- FAILED -> PENDING on manual retry and RUNNING -> PENDING on lease expiry.
    -- Decision is orthogonal to this and lives in its own column.
    status                   VARCHAR(16)  NOT NULL DEFAULT 'PENDING',
    -- The one-shot human verdict (3.1). Never overwritten, reversed or rewritten.
    decision                 VARCHAR(16)  NOT NULL DEFAULT 'PENDING',
    decision_by              BIGINT,
    decision_at              TIMESTAMPTZ,
    decision_comment         TEXT,
    -- Fencing metadata (2.1: "执行恢复不另建任务表"). A claim is a single atomic
    -- conditional update that increments the attempt, mints a token and writes a
    -- lease; every later write by that worker must match all three.
    execution_attempt        INTEGER      NOT NULL DEFAULT 0,
    execution_token          UUID,
    lease_until              TIMESTAMPTZ,
    -- Immutable input snapshot (3.5): the Requirement/AC text, the knowledge
    -- excerpts with their hashes, and the truncation/coverage manifest. History
    -- pages read this, never the pull request's current association.
    context_snapshot_json    JSONB,
    -- The review's own output summary -- 2.1 describes this row as carrying the
    -- 审查、上下文快照、摘要 and Decision. Per-AC verdicts (COVERED / NOT_FOUND /
    -- AT_RISK, 3.5) live here. Kept apart from context_snapshot_json on purpose:
    -- one is input, the other is output, and 3.5 forbids deriving review
    -- semantics from anything but the snapshot.
    summary_json             JSONB,
    -- Audit of what produced the result.
    engine                   VARCHAR(64),
    prompt_version           VARCHAR(64),
    model                    VARCHAR(128),
    created_at               TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at               TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT fk_review_pull_request
        FOREIGN KEY (project_id, pull_request_id) REFERENCES pull_request (project_id, id),
    -- Load-bearing pair. Under MATCH SIMPLE this three-column key is skipped
    -- entirely whenever any of its columns is NULL, so on its own it cannot stop
    -- a row that carries a requirement_id belonging to another project while
    -- leaving the revision NULL. ck_review_requirement_pairing is what removes
    -- that half-NULL state and therefore what makes the foreign key load-bearing
    -- -- the same shape as requirement_attachment's NOT NULL in batch 2 (D015.2).
    -- Delete the CHECK and this foreign key silently stops checking.
    CONSTRAINT fk_review_requirement_revision
        FOREIGN KEY (project_id, requirement_id, requirement_revision_id)
        REFERENCES requirement_revision (project_id, requirement_id, id),
    CONSTRAINT ck_review_requirement_pairing
        CHECK ((requirement_id IS NULL AND requirement_revision_id IS NULL)
            OR (requirement_id IS NOT NULL AND requirement_revision_id IS NOT NULL)),
    CONSTRAINT fk_review_decision_by FOREIGN KEY (decision_by) REFERENCES user_account (id),
    CONSTRAINT ck_review_status CHECK (status IN ('PENDING', 'RUNNING', 'COMPLETED', 'FAILED')),
    CONSTRAINT ck_review_decision CHECK (decision IN ('PENDING', 'APPROVE', 'REQUEST_CHANGES')),
    -- 2.2 verbatim: a pending decision carries no actor, and a final one must.
    CONSTRAINT ck_review_decision_fields CHECK (
        (decision = 'PENDING'
            AND decision_by IS NULL AND decision_at IS NULL AND decision_comment IS NULL)
        OR (decision IN ('APPROVE', 'REQUEST_CHANGES')
            AND decision_by IS NOT NULL AND decision_at IS NOT NULL)),
    -- design.md 2.7. Precondition 1 of 3.1 already says a decision may only be
    -- written to a COMPLETED review; this makes the unreachable combination
    -- unstorable rather than merely undetected. 2.2's list is a floor
    -- ("还必须具备"), not an exhaustive set.
    CONSTRAINT ck_review_decision_needs_completion
        CHECK (decision = 'PENDING' OR status = 'COMPLETED'),
    CONSTRAINT ck_review_attempt_non_negative CHECK (execution_attempt >= 0),
    -- A RUNNING review is one somebody claimed, so it must carry the fencing
    -- triple. Without this a lost update could leave a row RUNNING forever with
    -- no lease, which reconciliation could never reclaim.
    CONSTRAINT ck_review_running_is_leased CHECK (
        status <> 'RUNNING' OR (execution_token IS NOT NULL AND lease_until IS NOT NULL)),
    -- D003, and it must stay NULLS NOT DISTINCT. With the default NULLS DISTINCT
    -- a pull request with no requirement could accumulate unlimited rows sharing
    -- this identity: "the current Review" would stop being singular, the mapping
    -- table in PRD 5 would lose its meaning, and 3.1's "idempotently create or
    -- take" would no longer be idempotent.
    CONSTRAINT uq_review_identity UNIQUE NULLS NOT DISTINCT
        (pull_request_id, head_sha, review_input_fingerprint, requirement_revision_id),
    -- Composite parent target for finding.
    CONSTRAINT uq_review_project_id UNIQUE (project_id, id),
    -- Makes execution_attempt a key column, which is what lets finding's
    -- three-column foreign key fence a stale worker's inserts at the database
    -- rather than in application code. Measured: the application-level
    -- check-then-insert has a real TOCTOU window (design.md 6.1).
    CONSTRAINT uq_review_project_id_attempt UNIQUE (project_id, id, execution_attempt)
);

CREATE TABLE finding (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id              BIGINT       NOT NULL,
    review_id               BIGINT       NOT NULL,
    -- The attempt that produced this row. Not decoration: together with
    -- uq_review_project_id_attempt it is the fence, so a worker holding a stale
    -- attempt cannot insert here at all. The cost is explicit in design.md 6.2 --
    -- re-claiming must delete the abandoned attempt's findings in the same
    -- transaction, or a crashed worker pins the review forever.
    review_attempt          INTEGER      NOT NULL,
    requirement_id          BIGINT,
    requirement_revision_id BIGINT,
    ac_id                   BIGINT,
    finding_type            VARCHAR(32)  NOT NULL,
    -- Case sensitive, never lower-cased (3.4). path and line carry no database
    -- constraint by design: they have no parent column to agree with, and 3.5
    -- makes ReviewOutputValidator responsible for them (filePath must be inside
    -- changed files, the line must be verifiable in the patch). The database has
    -- no row-level view of the changed-file manifest and could not express it.
    path                    TEXT,
    line                    INTEGER,
    evidence                TEXT,
    status                  VARCHAR(16)  NOT NULL DEFAULT 'OPEN',
    assignee_id             BIGINT,
    -- D009. finding_key does batch dedup and cross-review matching; the two
    -- hashes decide whether a human rejection may be inherited, and neither may
    -- cover model prose -- otherwise suppression drifts with the model's wording.
    finding_key             VARCHAR(255) NOT NULL,
    evidence_hash           VARCHAR(64)  NOT NULL,
    basis_hash              VARCHAR(64)  NOT NULL,
    continuity              VARCHAR(16)  NOT NULL,
    carried_from_finding_id BIGINT,
    created_at              TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at              TIMESTAMPTZ  NOT NULL DEFAULT now(),
    -- 2.2: nullable composite foreign keys are MATCH SIMPLE, so none of the
    -- nullable keys below can prove the parent Review exists. This one is
    -- permanent and carries the attempt, so it fences as well as parents.
    CONSTRAINT fk_finding_review
        FOREIGN KEY (project_id, review_id, review_attempt)
        REFERENCES review (project_id, id, execution_attempt),
    CONSTRAINT fk_finding_acceptance_criterion
        FOREIGN KEY (project_id, requirement_revision_id, ac_id)
        REFERENCES acceptance_criterion (project_id, requirement_revision_id, id),
    -- Assignee points at project_member: leaving the project must revoke a live
    -- permission (2.3). The audit table below points at user_account instead.
    CONSTRAINT fk_finding_assignee
        FOREIGN KEY (project_id, assignee_id) REFERENCES project_member (project_id, user_id),
    CONSTRAINT fk_finding_carried_from
        FOREIGN KEY (project_id, carried_from_finding_id) REFERENCES finding (project_id, id),
    -- 2.2 verbatim, all three.
    CONSTRAINT ck_finding_requirement_pairing
        CHECK ((requirement_id IS NULL AND requirement_revision_id IS NULL)
            OR (requirement_id IS NOT NULL AND requirement_revision_id IS NOT NULL)),
    CONSTRAINT ck_finding_ac_needs_revision
        CHECK (ac_id IS NULL OR requirement_revision_id IS NOT NULL),
    CONSTRAINT ck_finding_code_quality_has_no_ac
        CHECK (finding_type <> 'CODE_QUALITY' OR ac_id IS NULL),
    CONSTRAINT ck_finding_type CHECK (finding_type IN ('CODE_QUALITY', 'REQUIREMENT')),
    -- PRD 5's human lifecycle. NOT_REPORTED is deliberately absent: 3.6 makes it
    -- a query-derived observation that must never be stored.
    CONSTRAINT ck_finding_status CHECK (status IN (
        'OPEN', 'CONFIRMED', 'IN_PROGRESS', 'FIXED', 'VERIFIED', 'CLOSED', 'REJECTED')),
    -- Orthogonal to status (PRD 5 forbids merging them into one field or one
    -- UI label), so it is a separate column with its own value set.
    CONSTRAINT ck_finding_continuity CHECK (continuity IN ('NEW', 'PERSISTING', 'SUPPRESSED')),
    -- 3.6.5: lineage exists exactly when the finding inherited something.
    CONSTRAINT ck_finding_carried_from_matches_continuity
        CHECK ((continuity = 'NEW' AND carried_from_finding_id IS NULL)
            OR (continuity IN ('PERSISTING', 'SUPPRESSED') AND carried_from_finding_id IS NOT NULL)),
    CONSTRAINT ck_finding_line_positive CHECK (line IS NULL OR line >= 1),
    CONSTRAINT uq_finding_project_id UNIQUE (project_id, id),
    -- 3.6.1: finding_key does within-batch dedup, so one review cannot report
    -- the same finding twice.
    CONSTRAINT uq_finding_review_key UNIQUE (review_id, finding_key)
);

CREATE TABLE finding_event (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id  BIGINT      NOT NULL,
    finding_id  BIGINT      NOT NULL,
    -- Points at the global account, not project_member: leaving a project must
    -- not erase an accomplished fact (2.3). Same rule as
    -- pull_request_requirement_event, and the opposite of finding.assignee_id.
    actor_id    BIGINT      NOT NULL,
    -- Names the intent; from/to name the mechanics. Both are recorded because a
    -- transition read back years later should not require re-deriving what the
    -- actor thought they were doing.
    action      VARCHAR(32) NOT NULL,
    from_status VARCHAR(16) NOT NULL,
    to_status   VARCHAR(16) NOT NULL,
    comment     TEXT,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_finding_event_finding
        FOREIGN KEY (project_id, finding_id) REFERENCES finding (project_id, id),
    CONSTRAINT fk_finding_event_actor FOREIGN KEY (actor_id) REFERENCES user_account (id),
    CONSTRAINT ck_finding_event_action CHECK (action IN (
        'CONFIRM', 'REJECT', 'CLAIM', 'MARK_FIXED', 'VERIFY', 'SEND_BACK', 'CLOSE', 'REOPEN')),
    CONSTRAINT ck_finding_event_from_status CHECK (from_status IN (
        'OPEN', 'CONFIRMED', 'IN_PROGRESS', 'FIXED', 'VERIFIED', 'CLOSED', 'REJECTED')),
    CONSTRAINT ck_finding_event_to_status CHECK (to_status IN (
        'OPEN', 'CONFIRMED', 'IN_PROGRESS', 'FIXED', 'VERIFIED', 'CLOSED', 'REJECTED')),
    -- The table records changes only. A row whose sides are equal is not one.
    CONSTRAINT ck_finding_event_is_a_change CHECK (from_status <> to_status)
);

-- ---------------------------------------------------------------- the trigger
--
-- 2.1 authorizes a constraint trigger for exactly one purpose, and 2.3 scopes
-- it precisely: Finding's requirement_id and requirement_revision_id must equal
-- the parent Review's, compared with IS NOT DISTINCT FROM so that "both NULL"
-- counts as equal. When the Review has no requirement, the Finding must have
-- neither column set.
--
-- Why a trigger and not a CHECK: a CHECK cannot contain a subquery (0A000).
-- Measured, a CHECK wrapping a lookup *function* is accepted by PostgreSQL 15
-- and does reject the bad child row, with better diagnostics than this trigger
-- -- but PostgreSQL only re-evaluates a CHECK when its own row changes, so that
-- form silently misses the parent-side half, and CHECK bodies are required to
-- be immutable, which a table lookup is not. 2.1 names a constraint trigger;
-- this is why that is the right instrument.
--
-- Why IMMEDIATE and not INITIALLY DEFERRED: deferring was measured to behave
-- better than feared -- no 25P02, the transaction stays usable, and COMMIT names
-- the offending finding id -- but it carries two traps. Inserting a bad row and
-- then correcting it still fails at COMMIT, and so does inserting one and then
-- deleting it, because deferred events bind to row versions rather than to the
-- transaction's final state. Deferral buys nothing here: a Finding's context is
-- copied from its parent at insert time, so no legitimate flow needs a
-- transient violation.

CREATE FUNCTION fp_finding_matches_review_context() RETURNS TRIGGER AS $fn$
DECLARE
    parent_requirement_id  BIGINT;
    parent_revision_id     BIGINT;
BEGIN
    SELECT r.requirement_id, r.requirement_revision_id
      INTO parent_requirement_id, parent_revision_id
      FROM review r
     WHERE r.project_id = NEW.project_id AND r.id = NEW.review_id;

    -- No "parent missing" branch: fk_finding_review is checked first and raises
    -- 23503 before this trigger ever runs, so such a branch would be dead code.

    IF NEW.requirement_id IS DISTINCT FROM parent_requirement_id
       OR NEW.requirement_revision_id IS DISTINCT FROM parent_revision_id THEN
        RAISE EXCEPTION
            'finding % context (requirement %, revision %) does not match review % (requirement %, revision %)',
            NEW.id, NEW.requirement_id, NEW.requirement_revision_id,
            NEW.review_id, parent_requirement_id, parent_revision_id
            USING ERRCODE = 'check_violation',
                  CONSTRAINT = 'ck_finding_matches_review_context';
    END IF;
    RETURN NULL;
END;
$fn$ LANGUAGE plpgsql;

CREATE CONSTRAINT TRIGGER ck_finding_matches_review_context
    AFTER INSERT OR UPDATE OF project_id, review_id, requirement_id, requirement_revision_id
    ON finding
    DEFERRABLE INITIALLY IMMEDIATE
    FOR EACH ROW EXECUTE FUNCTION fp_finding_matches_review_context();

-- 2.3 offers a choice for the parent-side half: have the trigger cover updates
-- to the parent's context columns, *or* refuse to let those identity columns
-- change after creation. This takes the second branch, which is both simpler
-- and stronger.
--
-- Stronger because these columns are the Review's identity (3.1's four-tuple)
-- plus the two 2.1 already calls immutable. Changing one turns this row into a
-- different Review, so nothing legitimate ever does it. And it closes a write
-- skew the measurements found the child trigger does not prevent: concurrently
-- inserting a Finding while updating the parent's context was only blocked as a
-- side effect of D003's unique key containing requirement_revision_id. With the
-- identity frozen, that interleaving cannot be constructed at all.

CREATE FUNCTION fp_review_identity_is_immutable() RETURNS TRIGGER AS $fn$
BEGIN
    IF NEW.pull_request_id IS DISTINCT FROM OLD.pull_request_id
       OR NEW.head_sha IS DISTINCT FROM OLD.head_sha
       OR NEW.review_input_fingerprint IS DISTINCT FROM OLD.review_input_fingerprint
       OR NEW.requirement_id IS DISTINCT FROM OLD.requirement_id
       OR NEW.requirement_revision_id IS DISTINCT FROM OLD.requirement_revision_id
       OR NEW.context_snapshot_json IS DISTINCT FROM OLD.context_snapshot_json THEN
        RAISE EXCEPTION 'review % identity and context snapshot are immutable after creation', OLD.id
            USING ERRCODE = 'check_violation',
                  CONSTRAINT = 'ck_review_identity_immutable';
    END IF;
    RETURN NEW;
END;
$fn$ LANGUAGE plpgsql;

CREATE TRIGGER ck_review_identity_immutable
    BEFORE UPDATE ON review
    FOR EACH ROW EXECUTE FUNCTION fp_review_identity_is_immutable();

-- ---------------------------------------------------------------- D015.1
--
-- Batch 2 created ai_call_log.review_id without a foreign key because review did
-- not exist yet, and left an assertion proving the column held only NULLs so
-- that adding the key later could not collide with history. That precondition
-- was measured to still hold; the key goes in now.

ALTER TABLE ai_call_log
    ADD CONSTRAINT fk_ai_call_log_review
    FOREIGN KEY (project_id, review_id) REFERENCES review (project_id, id);

-- ---------------------------------------------------------------- indexes

CREATE INDEX ix_review_pull_request ON review (project_id, pull_request_id);
CREATE INDEX ix_review_requirement_revision ON review (project_id, requirement_revision_id);
-- Reconciliation scans these two shapes: unclaimed PENDING, and RUNNING whose
-- lease has expired.
CREATE INDEX ix_review_status_lease ON review (status, lease_until);
CREATE INDEX ix_finding_review ON finding (project_id, review_id);
-- 3.6 matches finding_key across the reviews of one pull request.
CREATE INDEX ix_finding_key ON finding (project_id, finding_key);
-- PostgreSQL does not index the referencing side of a foreign key. Measured:
-- deleting 2000 findings took 7.04 s without this index and 176 ms with it.
CREATE INDEX ix_finding_carried_from ON finding (project_id, carried_from_finding_id);
CREATE INDEX ix_finding_event_finding ON finding_event (project_id, finding_id);
