-- Member directory, multi-role membership and user-owned SCM identities.
-- This is an append-only conversion of the V2/V5 shape; V1-V7 stay immutable.

ALTER TABLE user_account ADD COLUMN display_name VARCHAR(120);
UPDATE user_account SET display_name = username;
ALTER TABLE user_account ALTER COLUMN display_name SET NOT NULL;
ALTER TABLE user_account ADD CONSTRAINT ck_user_account_display_name_not_blank
    CHECK (btrim(display_name) <> '');

CREATE TABLE project_member_role (
    project_id BIGINT      NOT NULL,
    user_id    BIGINT      NOT NULL,
    role       VARCHAR(32) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT pk_project_member_role PRIMARY KEY (project_id, user_id, role),
    CONSTRAINT fk_project_member_role_member
        FOREIGN KEY (project_id, user_id) REFERENCES project_member (project_id, user_id),
    CONSTRAINT ck_project_member_role_role
        CHECK (role IN ('LEADER', 'DEVELOPER', 'REVIEWER'))
);

INSERT INTO project_member_role (project_id, user_id, role)
SELECT project_id, user_id, role FROM project_member;

CREATE UNIQUE INDEX ux_project_member_role_single_leader
    ON project_member_role (project_id) WHERE role = 'LEADER';

CREATE TABLE scm_identity (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id             BIGINT       NOT NULL,
    provider            VARCHAR(32),
    instance_identity   VARCHAR(255),
    external_user_id    VARCHAR(128) NOT NULL,
    external_username   VARCHAR(128) NOT NULL,
    label               VARCHAR(120) NOT NULL,
    usage_type          VARCHAR(16)  NOT NULL,
    verification_status VARCHAR(32)  NOT NULL,
    verification_method VARCHAR(32)  NOT NULL,
    verified_at         TIMESTAMPTZ,
    last_synced_at      TIMESTAMPTZ,
    created_at          TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT fk_scm_identity_user FOREIGN KEY (user_id) REFERENCES user_account (id),
    CONSTRAINT uq_scm_identity_user_id UNIQUE (user_id, id),
    CONSTRAINT ck_scm_identity_provider
        CHECK (provider IS NULL OR provider IN ('GITHUB', 'GITLAB')),
    CONSTRAINT ck_scm_identity_usage_type
        CHECK (usage_type IN ('WORK', 'PERSONAL', 'CLIENT', 'OTHER')),
    CONSTRAINT ck_scm_identity_verification_status
        CHECK (verification_status IN ('VERIFIED', 'LEGACY_UNCONFIRMED', 'REVOKED')),
    CONSTRAINT ck_scm_identity_verification_method
        CHECK (verification_method IN ('ONE_TIME_TOKEN', 'LEGACY_ADMIN_ASSERTED')),
    CONSTRAINT ck_scm_identity_label_not_blank CHECK (btrim(label) <> ''),
    CONSTRAINT ck_scm_identity_verified_shape CHECK (
        verification_status <> 'VERIFIED'
        OR (provider IS NOT NULL AND instance_identity IS NOT NULL
            AND verified_at IS NOT NULL AND last_synced_at IS NOT NULL
            AND verification_method = 'ONE_TIME_TOKEN')
    )
);

CREATE UNIQUE INDEX ux_scm_identity_verified_remote
    ON scm_identity (provider, instance_identity, external_user_id)
    WHERE verification_method = 'ONE_TIME_TOKEN';
CREATE INDEX ix_scm_identity_user ON scm_identity (user_id);

CREATE TABLE project_member_scm_binding (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id        BIGINT       NOT NULL,
    user_id           BIGINT       NOT NULL,
    scm_identity_id   BIGINT       NOT NULL,
    repository_id     BIGINT,
    status            VARCHAR(32)  NOT NULL,
    access_level      VARCHAR(16),
    access_checked_at TIMESTAMPTZ,
    requested_by      BIGINT,
    approved_by       BIGINT,
    requested_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    decided_at        TIMESTAMPTZ,
    activated_at      TIMESTAMPTZ,
    ended_at          TIMESTAMPTZ,
    created_at        TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at        TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT fk_member_scm_binding_member
        FOREIGN KEY (project_id, user_id) REFERENCES project_member (project_id, user_id),
    CONSTRAINT fk_member_scm_binding_identity
        FOREIGN KEY (user_id, scm_identity_id) REFERENCES scm_identity (user_id, id),
    CONSTRAINT fk_member_scm_binding_repository
        FOREIGN KEY (project_id, repository_id) REFERENCES scm_repository (project_id, id),
    CONSTRAINT fk_member_scm_binding_requested_by
        FOREIGN KEY (requested_by) REFERENCES user_account (id),
    CONSTRAINT fk_member_scm_binding_approved_by
        FOREIGN KEY (approved_by) REFERENCES user_account (id),
    CONSTRAINT ck_member_scm_binding_status CHECK (status IN (
        'PENDING_APPROVAL', 'ACTIVE', 'REJECTED', 'REVOKED',
        'SUPERSEDED', 'LEGACY_UNCONFIRMED')),
    CONSTRAINT ck_member_scm_binding_access_level
        CHECK (access_level IS NULL OR access_level IN ('READ', 'WRITE', 'ADMIN'))
);

CREATE UNIQUE INDEX ux_member_scm_binding_active
    ON project_member_scm_binding (project_id, user_id) WHERE status = 'ACTIVE';
CREATE UNIQUE INDEX ux_member_scm_binding_pending
    ON project_member_scm_binding (project_id, user_id) WHERE status = 'PENDING_APPROVAL';
CREATE INDEX ix_member_scm_binding_identity
    ON project_member_scm_binding (scm_identity_id);

-- Old Leader-entered values are retained as non-authorizing evidence. A loop
-- keeps the exact old member-to-identity mapping without adding a permanent
-- migration-only column to the new model.
DO $migration$
DECLARE
    legacy RECORD;
    identity_id BIGINT;
BEGIN
    FOR legacy IN
        SELECT pm.project_id, pm.user_id, pm.scm_external_user_id,
               COALESCE(pm.scm_username, pm.scm_external_user_id) AS scm_username,
               sr.id AS repository_id, sr.provider, sr.instance_identity
          FROM project_member pm
          LEFT JOIN scm_repository sr ON sr.project_id = pm.project_id
         WHERE pm.scm_external_user_id IS NOT NULL
    LOOP
        INSERT INTO scm_identity (
            user_id, provider, instance_identity, external_user_id,
            external_username, label, usage_type,
            verification_status, verification_method)
        VALUES (
            legacy.user_id, legacy.provider, legacy.instance_identity,
            legacy.scm_external_user_id, legacy.scm_username,
            'Legacy ' || legacy.scm_username, 'WORK',
            'LEGACY_UNCONFIRMED', 'LEGACY_ADMIN_ASSERTED')
        RETURNING id INTO identity_id;

        INSERT INTO project_member_scm_binding (
            project_id, user_id, scm_identity_id, repository_id, status)
        VALUES (
            legacy.project_id, legacy.user_id, identity_id,
            legacy.repository_id, 'LEGACY_UNCONFIRMED');
    END LOOP;
END
$migration$;

ALTER TABLE scm_repository
    ADD COLUMN identity_approval_required BOOLEAN NOT NULL DEFAULT FALSE;

DROP INDEX ux_project_member_single_leader;
ALTER TABLE project_member
    DROP COLUMN role,
    DROP COLUMN scm_external_user_id,
    DROP COLUMN scm_username,
    DROP COLUMN scm_identity_verified_at;
