<script setup lang="ts">
import { computed, onMounted, ref, watch } from "vue";
import { RouterLink, useRoute, useRouter } from "vue-router";
import { knowledgeRoute, parseId, projectMembersRoute, PROJECT_QUERY_KEY, repositoriesRoute, requirementsRoute, reviewDetailRoute, reviewsRoute } from "../../app/routes";
import { formatDateTime } from "../../lib/datetime";
import { apiErrorMessage } from "../../lib/http";
import { listProjectKnowledge, type KnowledgeDocument } from "../knowledge/api";
import { listProjects, type Project } from "../project/api";
import { listRequirements, type RequirementSummary } from "../requirement/api";
import { listProjectReviews, listReviewActivity, type ActivityView, type ProjectReviewRow } from "../review/api";
import { REVIEW_ACTIVITY_LABELS } from "../review/labels";
import { listScmRepositories, type ScmRepository } from "../scm/api";

const route = useRoute(); const router = useRouter();
const projectId = computed(() => parseId(route.query[PROJECT_QUERY_KEY]));
const projects = ref<Project[]>([]); const requirements = ref<RequirementSummary[]>([]); const activity = ref<Record<string, ActivityView>>({}); const reviews = ref<ProjectReviewRow[]>([]); const knowledge = ref<KnowledgeDocument[]>([]); const repositories = ref<ScmRepository[]>([]); const loading = ref(false); const error = ref<string | null>(null);
const selected = computed(() => projects.value.find((project) => project.id === projectId.value) ?? null);
const embeddedChunks = computed(() => knowledge.value.reduce((total, document) => total + document.embeddedChunkCount, 0));
const readyKnowledge = computed(() => knowledge.value.filter((document) => document.status === "READY").length);
const requirementStatus = computed(() => requirements.value.reduce<Record<string, number>>((counts, requirement) => ({ ...counts, [requirement.status]: (counts[requirement.status] ?? 0) + 1 }), {}));
const activityDistribution = computed(() => Object.values(activity.value).reduce<Record<string, number>>((counts, item) => ({ ...counts, [item.activity]: (counts[item.activity] ?? 0) + 1 }), {}));
function selectProject(event: Event): void { const id = parseId((event.target as HTMLSelectElement).value); if (id !== null) void router.push({ name: "workspace", query: { [PROJECT_QUERY_KEY]: String(id) } }); }
async function load(): Promise<void> { const id = projectId.value; requirements.value=[]; activity.value={}; reviews.value=[]; knowledge.value=[]; repositories.value=[]; error.value=null; if(id===null)return; loading.value=true; try { [requirements.value, activity.value, reviews.value, knowledge.value, repositories.value] = await Promise.all([listRequirements(id), listReviewActivity(id), listProjectReviews(id), listProjectKnowledge(id), listScmRepositories(id)]); } catch(failure: unknown) { error.value=apiErrorMessage(failure); } finally { loading.value=false; } }
onMounted(async()=>{try{projects.value=await listProjects();}catch(failure:unknown){error.value=apiErrorMessage(failure);}}); watch(projectId,load,{immediate:true});
</script>
<template>
 <section aria-labelledby="workspace-title"><div class="page-head"><p class="eyebrow">Project workbench</p><h1 id="workspace-title">工作台</h1><p class="lede">用真实项目数据串起需求质量、知识增强实现建议与唯一 AI 审查引擎；AI 只给出证据与建议，业务状态和最终决定始终由人完成。</p></div>
 <section class="panel project-selector"><div><h2 class="panel-title">当前项目</h2><p class="field-hint">工作台只聚合现有接口，不创建新的指标或后台数据。</p></div><div class="field"><label for="workspace-project">项目</label><select id="workspace-project" :value="projectId ?? ''" @change="selectProject"><option value="" disabled>请选择项目</option><option v-for="project in projects" :key="project.id" :value="project.id">{{ project.name }}</option></select></div></section>
 <p v-if="projectId===null" class="empty-state">选择一个项目以查看研发上下文。</p><template v-else><p v-if="error" class="alert" role="alert">{{ error }}</p><p v-else-if="loading" class="muted">正在汇聚项目工作台…</p><template v-else>
  <section class="ai-chain" aria-labelledby="ai-chain-title"><h2 id="ai-chain-title" class="visually-hidden">AI 能力链</h2><article class="panel ai-step"><p class="eyebrow">01 · Requirement Quality</p><h3>需求质量检查</h3><p>输入：需求正文与验收标准。输出：规则发现与结构化 AI 建议。</p><RouterLink class="button button-quiet" :to="requirementsRoute(projectId)">进入需求</RouterLink></article><article class="panel ai-step"><p class="eyebrow">02 · Knowledge-enhanced</p><h3>实现建议</h3><p>输入：需求、AC 与向量召回的项目知识。输出：清单、规则与风险。</p><RouterLink class="button button-quiet" :to="knowledgeRoute(projectId)">查看知识索引</RouterLink></article><article class="panel ai-step"><p class="eyebrow">03 · Single Review Engine</p><h3>AI 代码审查</h3><p>输入：Requirement、AC、向量知识与 Diff。输出：可核验 Finding；人工决定闭环。</p><RouterLink class="button button-quiet" :to="reviewsRoute(projectId)">进入审查</RouterLink></article></section>
  <section class="pulse-grid" aria-label="项目脉搏"><div class="panel"><strong>{{ requirements.length }}</strong><span>研发需求</span><small>{{ Object.entries(requirementStatus).map(([status,count])=>`${status} ${count}`).join(" · ") || "暂无" }}</small></div><div class="panel"><strong>{{ reviews.length }}</strong><span>审查记录</span><small>{{ Object.entries(activityDistribution).map(([status,count])=>`${REVIEW_ACTIVITY_LABELS[status as keyof typeof REVIEW_ACTIVITY_LABELS]} ${count}`).join(" · ") || "暂无审查活动" }}</small></div><div class="panel"><strong>{{ embeddedChunks }}</strong><span>向量索引 Chunk</span><small>{{ readyKnowledge }}/{{ knowledge.length }} 文档已就绪</small></div><div class="panel"><strong>{{ repositories.length }}</strong><span>SCM 仓库</span><small>{{ repositories[0]?.provider ?? "尚未接入" }}</small></div></section>
  <div class="workspace-grid"><section class="panel"><div class="index-head"><div><h2 class="panel-title">最近需求</h2><p class="field-hint">状态与派生审查活动分别呈现。</p></div><RouterLink class="button button-quiet" :to="requirementsRoute(projectId)">全部需求</RouterLink></div><p v-if="requirements.length===0" class="empty-state">还没有需求。</p><ol v-else class="record-list"><li v-for="requirement in requirements.slice(0,5)" :key="requirement.id" class="record"><RouterLink :to="{name:'requirement-detail',params:{id:String(requirement.id)},query:{project:String(projectId)}}"><strong>{{ requirement.title }}</strong></RouterLink><p class="muted">{{ requirement.status }} · {{ activity[String(requirement.id)]?.activity ?? '未返回审查活动' }} · {{ formatDateTime(requirement.updatedAt) }}</p></li></ol></section><section class="panel"><div class="index-head"><div><h2 class="panel-title">最近审查</h2><p class="field-hint">单一 AI Review Engine 的执行记录。</p></div><RouterLink class="button button-quiet" :to="reviewsRoute(projectId)">全部审查</RouterLink></div><p v-if="reviews.length===0" class="empty-state">还没有 Review。</p><ol v-else class="record-list"><li v-for="review in reviews.slice(0,5)" :key="review.id" class="record"><RouterLink :to="reviewDetailRoute(projectId,review.id)"><strong>Review {{ review.id }} · PR #{{ review.pullRequestNumber }}</strong></RouterLink><p class="muted">{{ review.status }} · Decision {{ review.decision }} · {{ formatDateTime(review.createdAt) }}</p></li></ol></section></div>
  <section v-if="selected" class="panel shortcuts"><h2 class="panel-title">项目快捷入口</h2><RouterLink class="button" :to="projectMembersRoute(selected.id)">成员</RouterLink><RouterLink class="button" :to="repositoriesRoute(selected.id)">仓库接入</RouterLink><RouterLink class="button" :to="knowledgeRoute(selected.id)">项目知识</RouterLink></section>
 </template></template></section>
</template>
<style scoped>
.ai-chain,.pulse-grid,.workspace-grid{display:grid;gap:var(--fp-space-5);grid-template-columns:repeat(3,minmax(0,1fr));}.ai-step{margin-bottom:var(--fp-space-2);border-color:var(--fp-color-border-accent)}.ai-step h3{margin:0;font-size:1.1rem}.ai-step p:not(.eyebrow){color:var(--fp-color-text-muted);line-height:1.65}.pulse-grid{grid-template-columns:repeat(4,minmax(0,1fr));}.pulse-grid .panel{display:grid;gap:var(--fp-space-2);margin-bottom:var(--fp-space-6)}.pulse-grid strong{font:800 1.7rem/1 var(--fp-font-mono);color:var(--fp-color-accent-inverse)}.pulse-grid span{font-weight:700}.pulse-grid small{color:var(--fp-color-text-muted)}.workspace-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.shortcuts{display:flex;align-items:center;flex-wrap:wrap;gap:var(--fp-space-3)}.shortcuts h2{width:100%;margin-bottom:0}@media(max-width:64rem){.ai-chain,.pulse-grid{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:42rem){.ai-chain,.pulse-grid,.workspace-grid{grid-template-columns:1fr}}
</style>
