<template>
  <div class="knowledge-paper">
    <section class="ink-panel head"><div><span class="ink-eyebrow">项目知识库</span><h1>知识卷宗</h1><p>上传、索引状态、重建、删除与检索测试共用既有 useKnowledge 状态。</p></div><button v-if="canReindex" class="ink-outline-button" :disabled="busy" @click="$emit('reindex')">重建索引</button></section>
    <section v-if="canUpload" class="ink-panel upload-panel"><h2>上传文档</h2><div class="upload-grid"><select :value="docType" @change="$emit('doc-type',$event.target.value)"><option value="BUSINESS_FLOW">业务流程</option><option value="REVIEW_RULE">审查规则</option><option value="README">README</option><option value="ARCHITECTURE">架构文档</option></select><input type="file" accept=".txt,.md,.markdown" @change="$emit('file',$event)" /><button class="ink-primary-button" :disabled="busy" @click="$emit('upload')">上传入库</button></div></section>
    <section v-else class="ink-panel permission-note">当前角色可读取和检索，但不能上传、重建或删除知识文档。</section>
    <section class="ink-panel"><header><div><span class="ink-eyebrow">文档列表</span><h2>{{ documents.length }} 篇</h2></div><button class="ink-outline-button" @click="$emit('refresh')">刷新</button></header><p v-if="loading" class="state">正在读取文档…</p><p v-else-if="!documents.length" class="state">暂无知识文档。</p><ul v-else class="doc-list"><li v-for="doc in documents" :key="doc.documentId"><div><strong :title="doc.fileName">{{ doc.fileName }}</strong><span>{{ doc.docType }} · {{ doc.status }}</span></div><time>{{ fmtTime(doc.createdAt) }}</time><button v-if="canDelete" class="ink-danger-button" @click="$emit('delete',doc.documentId)">删除</button></li></ul></section>
    <section class="ink-panel search-panel"><span class="ink-eyebrow">检索测试</span><h2>验证召回内容</h2><div class="search-row"><textarea :value="query" rows="3" maxlength="4000" @input="$emit('query',$event.target.value)" /><button class="ink-primary-button" :disabled="busy || !query.trim()" @click="$emit('search')">检索</button></div><p v-if="searched && !matches.length" class="state">没有命中内容。</p><ol v-else class="matches"><li v-for="(match,index) in matches" :key="`${match.documentId}-${match.chunkIndex}-${index}`"><header><strong>{{ match.sourceName || match.fileName || `文档 #${match.documentId}` }}</strong><span>{{ match.score == null ? '' : Number(match.score).toFixed(3) }}</span></header><pre>{{ match.content || match.text || match.excerpt }}</pre></li></ol></section>
  </div>
</template>
<script setup>
import { fmtTime } from '../../utils/format.js'
defineProps({documents:{type:Array,default:()=>[]},docType:{type:String,default:'BUSINESS_FLOW'},query:{type:String,default:''},matches:{type:Array,default:()=>[]},searched:Boolean,loading:Boolean,busy:Boolean,canUpload:Boolean,canReindex:Boolean,canDelete:Boolean})
defineEmits(['doc-type','file','upload','reindex','delete','refresh','query','search'])
</script>
<style scoped>.knowledge-paper{display:grid;gap:var(--ink-sp-16)}.ink-panel{padding:var(--ink-sp-24);background:var(--ink-wash-panel);border:1px solid var(--line-soft);border-radius:var(--ink-radius-paper);box-shadow:var(--ink-shadow-panel)}.head,header{display:flex;justify-content:space-between;align-items:flex-start;gap:var(--ink-sp-12)}h1,h2{margin:var(--ink-sp-4) 0;font-family:var(--ink-font-display)}p,.state,.permission-note{color:var(--ink-muted)}.upload-grid,.search-row{display:grid;grid-template-columns:200px 1fr auto;gap:var(--ink-sp-12);align-items:end}.upload-grid select,.upload-grid input,.search-row textarea{min-height:44px;padding:var(--ink-sp-8);border:1px solid var(--line-soft);background:var(--ink-wash-field);color:var(--ink-default);font:inherit}.doc-list,.matches{list-style:none;margin:var(--ink-sp-16) 0 0;padding:0;display:grid;gap:var(--ink-sp-8)}.doc-list li{display:grid;grid-template-columns:minmax(0,1fr) auto auto;gap:var(--ink-sp-12);align-items:center;min-height:52px;padding:var(--ink-sp-8) var(--ink-sp-12);border-bottom:1px solid var(--line-soft)}.doc-list strong,.doc-list span{display:block;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.doc-list span,.doc-list time{color:var(--ink-muted);font-size:var(--ink-fs-12)}.matches li{padding:var(--ink-sp-12);border:1px solid var(--line-soft);background:var(--surface-paper)}.matches pre{max-height:220px;overflow:auto;white-space:pre-wrap;word-break:break-word;color:var(--ink-default);font-family:var(--ink-font-code);font-size:var(--ink-fs-12)}@media(max-width:760px){.upload-grid,.search-row{grid-template-columns:1fr}.doc-list li{grid-template-columns:1fr auto}.doc-list time{grid-column:1}}</style>
